yseop/vscode-yseopml

README.adoc
* Links in asciidoctor are `http://blabla[text]` (it's not like in Markdown).
* Improved (or so I hope) text.
* Created the attribute `{vsc}` to make it easier to type `VS Code` (while being consistent).
…
=> chore(readme): reread, fix links, improve formatting

README.adoc, package.json
1. It seems perfectly useless to make sure the working directory is the same at the end of an npm script and at the beginning.
2. I tend to use subshells spawned through parentheses in order to restore the previous working directory instead of using `cd ..`, etc. Among other benefits, it makes it useless to use weird conditions like `&&` when trying to guess if we succeeded in going to a directory or not. Basically, I went from `cd a && cmd && cd ..` to `cd a && { cmd; cd .. }` and finally to `(cd a && cmd)`. The first form, which was used before my edits, is not really robust as it leaves the working directory changed to `a` if `cmd` fails.
3. Updated doc to tell people to install the `vsce` module locally. This seems to help `npm` to find it when running the `package` script.
4. More …
=> feat(npm): updated scripts and related doc

package.json
Former scripts didn't work because of the parenthesis.
=> fix(package.json): fix package .json scripts for Windows

client/syntaxes/yml.tmLanguage.json
=> fix(color): fix syntax coloring of comments in function arguments

client/CHANGELOG.md, client/package.json, client/src/extension.ts
Allow to connect somehow Yseop CLI with VSCode extension by adding a new parameter and two new commands.
→ We can also think of adding shortcuts to the new commands?
=> feat(yseopCliCommands): use Yseop CLI batch + compile as VSCode command

release.sh
This should ensure we do not place the tag on an old commit. Also tried to make things easier for the user.
=> fix(releaseScripts): better way to tag releases

package-lock.json, package.json, server/package-lock.json, server/package.json, server/src/definitions/DefinitionUtils.ts, server/src/definitions/YmlDefinitionProvider.ts, server/src/server.ts, server/src/test/DefinitionUtils.test.ts, server/src/test/YmlKaoFileVisitor.test.ts, server/src/visitors/VisitorsUtils.ts, server/src/visitors/YmlClassVisitor.ts, server/src/visitors/YmlFunctionVisitor.ts, server/src/visitors/YmlKaoFileVisitor.ts, server/src/visitors/YmlObjectInstanceVisitor.ts
Before this PR, we search the possibles definitions from the first entity name candidate found before the cursor position.
This means that if we have `i|nput` where `|` is the cursor, we will search for all the definitions containing `i`.
Worse, if we have `entityName:;*/-*|)=)=)` we will find `entityName`.
In this PR, with the first example we will search for `input` and with second nothing will be possible, since the cursor isn't on a specific entityName, but in the middle of some noise.
=> feat: find the definitions from a full token and not a part of it

client/CHANGELOG.md
Since we don"t have yet a way to update the version number in the CHANGELOG file, we need a commit to set the version it.
Also, pushing in a release branch seems impossible :/
=> chore(release): set version in changelog

client/package.json, client/src/extension.ts
This PR adds the possibility to parse all the files that should be handled by this extension at startup.
It also adds an option to disable this feature, since it can be a little bit expensive.
There is probably a more efficient way to do so, but I don't have efficient ways to find better solution now (I'm in a train).
At least this change can be easily disabled if needed and it should help a lot when coding with an YML project.
=> feat: parse the whole project; new option to disable this feature

CHANGELOG.md, client/src/extension.ts
The goal of this PR is to improve the way we parse the whole project.
Now, instead of parsing every files that have the correct extension, we parse the `project.kao` file and check all of the files it references and then parse all of them. This is done recursively.
We then parse `yclass`, `yobject` and `ycomplete` files.
So, most of the files parsed are now files that are more or less referenced for the project. No more YAML files parsed, for example!
=> perf(parsing): improve “parse the whole project” feature

server/src/server.ts
Didn't get the correct setting value because the wrong name was used in the code.
=> fix: get the real setting name

server/src/engineModel/EngineModel.ts
PR for future devs on binarisation of `lib/` directory.
It implies to have a `predefinedObjects.xml` which handles the `lib/` definitions instead of parsing this directory.
It implies that we need to get an access to the doc from this XML file instead of the code itself.
=> feat: get documentation if any; avoid missing ident case in tag

CHANGELOG.md, client/package-lock.json, client/src/test/test.kao, server/src/definitions/YmlDefinitionProvider.ts, server/src/server.ts, server/src/visitors/YmlFunctionVisitor.ts, server/src/yml-objects/AbstractYmlFunction.ts
In this PR I apply the two suggestions brought by @mminot-yseop about the use of `pop()` and the comment.
> So it can be declared in several places? Hum… D’you mean, like, not technically the same method, but homonyms throughout the workspace, for example? Or is this a YML feature consisting of declaring the same symbol multiple times?
Also, I try to answer his concerns about the fact that we are mixing declaration and implementation. It should be clearer now, even though it is not perfect yet.
I also fix a security issue reported by `npm audit`.
=> feat(defs): use go to implementation feature

CHANGELOG.md, server/src/server.ts
In a `M` type `*.kao` file, paths are relative to the current *.kao file’s directory.
In a `F` type `*.kao` file, paths are relative to the project's root.
In this PR we assume that the root is the workspace path.
=> feat: differentiate filetype F and M for kao files

language-configuration.json
In this PR we add parenthesis as `brackets`, meaning that parenthesis now increase indentation level when creating a new line after `(` and decrease the indentation level after `)`. No impact if both are on the same line.
Also we add parenthesis as `autoclosingPairs`.
=> feat(languageconf): improve language conf

client/package-lock.json, client/package.json, package-lock.json, package.json, server/src/engineModel/EngineModel.ts, server/src/server.ts, server/src/test/EngineModel.test.ts, server/src/test/YmlCompletionItemsProvider.test.ts, server/src/test/YmlKaoFileVisitor.test.ts, server/src/visitors/YmlClassVisitor.ts, server/src/visitors/YmlEnumVisitor.ts, server/src/visitors/YmlFunctionVisitor.ts, server/src/visitors/YmlObjectInstanceVisitor.ts, server/src/visitors/YmlVisitorHelper.ts, server/src/visitors/index.ts, server/src/yml-objects/AbstractYmlObject.ts, server/src/yml-objects/YmlAttribute.ts, server/src/yml-objects/YmlClass.ts, server/src/yml-objects/YmlEnum.ts, server/src/yml-objects/YmlEnumMember.ts, server/src/yml-objects/YmlFunction.ts, server/src/yml-objects/YmlMethod.ts, server/src/yml-objects/YmlObjectInstance.ts
In this PR I change how we handle hover messages as well as some documentation provided by the completion list.
I thought it was sad to have no documentation or `Not Documented` when hovering elements while we can at least provide elements signature.
I tried to find a format that's not too awful.
It allows to have that kind of elements to be displayed.
```
(variable) indicatorProperty_concept ⇒ NlgApplication||NlgLambdaTerm
(method) [LibDocument:ConceptsWriter].buildDefaultReferentialExpression ⇒ NlgApplication,NlgLambdaTerm
(instance) [GLOBAL] LibOntology:DerivedTree:MC2 ⇒ ConstList
(function) [STATIC] logWarning
(method) [Collection].get
(class) HashSet extends yseop.collection.Collection
```
This detailed part is displayed when hovering elements or in the suggestion list.
When …
=> feat(hover): better hover messages

.vscode/launch.json, server/src/completion/YmlCompletionItemsProvider.ts, server/src/features/CompletionResolveRequestHandler.ts, server/src/features/index.ts, server/src/server.ts, server/src/test/CompletionResolveRequestHandler.test.ts, server/src/yml-objects/AbstractYmlObject.ts
This PR fixes an issue that happens from version 1.9.0.
In a very large project, when there is a huge amount of completion items, writing text after an identifier provokes any further communication between client and server to be blocked.
This can be seen because hover, outline, parsing, etc… never updates anymore.
In large projects with a lot of elements, we were sending to the client way too many information. This was blocking the client during deserialization.
_But why was it working before 1.9.0?_
Starting version 1.9.0, we send to the client everything we find − not only the elements with documentation. That makes the amount of elements we send way higher than before. On top of that, now every element − more or less − has at least its `detail` attribute set. That also makes the …
=> fix(completion): complete completion items on resolve event

server/src/features/CompletionResolveRequestHandler.ts
There was a remaining issue when using the completion resolve request too many times. It happens to be due to the server sending full AbstractYmlObject objects. These objects are too heavy for the client when the list is too long.
Sending just the good amount of data (type, label, details and documentation) instead of the full objects solves the issue.
We'll be able to do a new release after this fix is merged.
=> fix(completion): stop sending full object on completion resolve request

client/resources/kb/_technical/formatted/collectionsAndIfElse.dcl, client/resources/kb/_technical/formatted/otherDocumentFormat.dcl, client/resources/kb/_technical/toFormat/collectionsAndIfElse.dcl, client/src/test/extension.test.ts, server/src/server.ts, server/src/visitors/YmlBaseVisitor.ts
In this PR I extend the document format so that collections-like elements and if-else expressions are handled too.
I also managed to create small functions to set one space between elements.
It should reduce the time required for further developments.
Unfortunately, I didn't manage to remove spaces between the last element of a collection and the end of the collection itself
```
// This won't change with document format.
{firstElement, lastElement     };
```
I'll do the devs in another PR later. I don't plan a release this month, anyway.
By the way, the difference between a token and a parser rule context, basically, is that a token is a terminal symbol, a leaf of the parsing tree, while a parser rule context is a node of the tree.
To understand the effects of the new code, I recommend …
=> feat(format): improve formatter

client/src/extension.ts
An open and active editor was required to launch a command.
This doesn't make sense so I removed this requirement.
=> feat: no need of an active text editor to launch commands

CHANGELOG.md, server/src/definitions/DefinitionUtils.ts, server/src/test/DefinitionUtils.test.ts, server/src/test/FoldingRangesRequestHandler.test.ts, server/src/visitors/YmlClassVisitor.ts, server/src/visitors/YmlEnumVisitor.ts
Allow using Go To Definition (shortcut F12) on class names.
Useful to check parent classes.
In the ticket I also wanted to take into account `complete` instructions, but it would require more devs than expected, so I won't do it here.
I need to think of a nice way to differentiate `complete MyObject;` from `complete MyClass;`, for instance.
I also wanted to make the Go To Definition point directly to predefinedObjects.xml file when a user has defined one, but the parser I use doesn't have any clue on the current line.
Sorry.
See https://yseop-knowledge.atlassian.net/browse/VSC-12
=> feat(gotodef): go to definition on classnames

CHANGELOG.md, server/src/features/DocumentFormattingRequestHandler.ts, server/src/server.ts, server/src/test/DocumentFormatRequestHandler.test.ts
We were using the value of configuration set at startup (which was null) instead of the dynamicaly computed configuration. The issue happened not only on the file sent by @obatier-yseop but in any other file too.
Maybe this PR code coverage won't pass because I had to do some changes on `server.ts`.I will merge it anyway ^^'.
Another PR (#205) will make code coverage way better once finished.
=> fix: use dynamic document format settings instead of null one
