README.adoc, client/README.md
=> doc(snippets): add list and, in a comment, a command to update it

Jenkinsfile
=> feat(jenkins) build

client/package.json
=> fix(properties): replaced YML settings title

client/CHANGELOG.md, client/package.json, client/src/extension.ts
Still need to fix the fact that we don't get the standard output of these commands in VSCode messages. :thinking:
=> feat(cliCmds): new CLI commands in VSCode

client/package.json, client/src/extension.ts, package.json
− Help user to change its settings
− Display some messages in a more user-friendly way
− Update of the settings taken into account directly
=> feat(UX): improve user experience

release.sh
Write date in changelog, update version number, package, commit, push.
=> feat(releaseScripts): basic script to produce a release branch

client/package-lock.json, client/package.json
version 3.3.6 has security vulnerabilities
=> chore(security): force event-stream version 3.3.4

client/CHANGELOG.md, client/server/ClassVisitor.js, client/server/package-lock.json, client/server/server.js, server/src/ClassVisitor.ts, server/src/server.ts
The purpose of this PR is to give access to YML classes attributes documentation, if any, when using the autocompletion.
=> feat(documentation): autocomplete gives class attribute documentation

client/test/extension.test.ts
see https://stackoverflow.com/a/45858343/3577898
=> feat: better failure when failing promise

client/package-lock.json, client/package.json
=> fix: fix vulnerability

client/CHANGELOG.md, client/README.md, client/language-configuration.json, client/snippets/snippets.json
=> feat: remove "\if" automatic tag; add "\if" and "\if \else" snippets

client/CHANGELOG.md, client/syntaxes/yml.tmLanguage.json
See https://github.com/yseop/vscode-yseopml/issues/78
=> fix: syntax highlighting

client/CHANGELOG.md, server/src/completion/YmlCompletionItemsProvider.ts, server/src/definitions/DefinitionUtils.ts, server/src/server.ts, server/src/test/DefinitionUtils.test.ts
=> feat: hovering known elements displays their documentation 

release.sh
Couldn't find an option to get 4-space indentation from `jq`, so I used the one that makes it spew hard tabs and them twisted them into what I wanted.
This should avoid having huge diffs on `package.json` files before and after releases. :sweat_smile:
=> fix(release): use 4-space indentation after jq

server/src/server.ts
Thank you for your integration work xD
=> fix: get documentation for full labels too

.prettierrc, CHANGELOG.md, client/src/test/test.kao, server/src/definitions/DefinitionUtils.ts, server/src/definitions/YmlDefinitionProvider.ts, server/src/server.ts, server/src/test/YmlCompletionItemsProvider.test.ts, server/src/test/YmlKaoFileVisitor.test.ts, server/src/visitors/YmlClassVisitor.ts, server/src/visitors/YmlFunctionVisitor.ts, server/src/yml-objects/AbstractYmlFunction.ts, server/src/yml-objects/YmlMethod.ts
Improved definition provider. 
`Go To Definition` on a method name gives the list of the locations where the method is declared and where it is implemented.
=> feat: function implementation Location

.vscodeignore, CHANGELOG.md, client/src/extension.ts, package-lock.json, package.json, server/package-lock.json, server/package.json, server/src/server.ts
In this PR we move the whole parsing work to the server-side, avoiding to do as many calls to the server as there are files to parse.
This was making the extension crash sometimes because of potential memory leaks. This PR fixes this issue too.
**NOTE**: I'll do a release after this one.
=> feat(parse): parse project client-side; avoid leak warning

CHANGELOG.md, client/package-lock.json, client/package.json, package-lock.json, package.json, server/package-lock.json, server/package.json
Just update version numbers and CHANGELOG date.
Last commit before PR to master for official release.
=> chore: prepare release v1.7.0

server/src/definitions/YmlDefinitionProvider.ts, server/src/features/DocumentSymbolRequestHandler.ts, server/src/test/YmlDefinitionProvider.test.ts, server/src/test/YmlParsingErrorListener.test.ts, server/src/visitors/YmlParsingErrorListener.ts
For an unknown reason the build for https://github.com/yseop/vscode-yseopml/pull/162 is not done. I cherry-picked the interesting commits and I will close that PR.
=> test: error listener; definition provider

.vscode/launch.json, CHANGELOG.md, client/package-lock.json, client/package.json, package-lock.json, package.json, server/package-lock.json, server/package.json, server/src/completion/YmlCompletionItemsProvider.ts, server/src/definitions/YmlDefinitionProvider.ts, server/src/features/CompletionResolveRequestHandler.ts, server/src/features/DocumentSymbolRequestHandler.ts, server/src/features/index.ts, server/src/server.ts, server/src/test/CompletionResolveRequestHandler.test.ts, server/src/test/YmlDefinitionProvider.test.ts, server/src/test/YmlParsingErrorListener.test.ts, server/src/visitors/YmlParsingErrorListener.ts, server/src/yml-objects/AbstractYmlObject.ts
=> chore(release): version 1.9.1

client/package-lock.json, client/package.json, package-lock.json, package.json
Now, there should be 0 vulnerabilities remaining.
Reading the build logs on Jenkins should be enough to check if it's true.
=> chore(dependencies): update dependencies

CHANGELOG.md, syntaxes/yml.tmLanguage.YAML-tmLanguage, syntaxes/yml.tmLanguage.json
@vholten-yseop 
Should be better now.
Try it and tell me what do you think.
=> fix: highlighting is not correct between quote escape sequences

client/package-lock.json, client/package.json, client/src/extension.ts, package-lock.json, package.json
I'm having fun exploring the VSCode API.
I added a KB selector when a project contains multiple KB.
I also added a progress bar :)
=> feat: add project picker and progress bar

client/package-lock.json, client/package.json, client/src/extension.ts, package-lock.json, server/package-lock.json, server/package.json, server/src/server.ts
Just some dependency upgrades.
=> chore: update dependencies for lsp 7.0.0

CHANGELOG.md, package-lock.json, package.json, server/package-lock.json, server/package.json, server/src/engineModel/EngineModel.ts, server/src/server.ts, server/src/serverUtils.ts, server/src/test/EngineModel.test.ts, server/src/test/ServerUtils.test.ts, server/src/yml-objects/AbstractYmlObject.ts
The goal here is when using Go To Definition feature being able to directly go to the correct position in the user defined `predefinedObjects.xml` file.
=> feat: go to def to predefined objects XML file − VSC-15

server/src/engineModel/EngineModel.ts, server/src/test/EngineModel.test.ts
Bug on the develop branch.
This will fix the issue.
=> fix: extract cdata context correctly

server/src/constants.ts, server/src/engineModel/EngineModel.ts, server/src/features/DocumentFormattingRequestHandler.ts, server/src/features/index.ts, server/src/server.ts, server/src/serverUtils.ts, server/src/test/DocumentFormatRequestHandler.test.ts, server/src/test/ProjectUtils.test.ts, server/src/test/YmlParsingErrorListener.test.ts, server/src/visitors/YmlParsingErrorListener.ts, server/src/visitors/YmlVisitorHelper.ts
In this PR I:
* moved the dependency to the connection to a single file, making it easier to share
* moved the document formatting handler tests
* moved the code that looks for dependencies through kao files
* added tests for this code
=> feat: improve server-side code coverage
